# Generated by Django 3.0.2 on 2020-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
