# Generated by Django 3.0.2 on 2020-02-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200203_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=set(),
        ),
    ]
