# Generated by Django 3.0.2 on 2020-02-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200203_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Course'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Teacher'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('course', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('course', 'student')},
        ),
    ]
