# Generated by Django 3.0.2 on 2020-02-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200203_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='account',
            new_name='manager_id',
        ),
    ]
