# Generated by Django 3.0.2 on 2020-02-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200205_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTeacher',
            new_name='TeacherCourse',
        ),
    ]
