# Generated by Django 3.0.2 on 2020-02-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200206_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_course',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='common.Course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='common.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='common.Teacher'),
        ),
    ]
