# Generated by Django 3.0.2 on 2020-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200227_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.CharField(default='', max_length=200),
        ),
    ]
