# Generated by Django 3.0.2 on 2020-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20200227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.CharField(default='正常签到！', max_length=200),
        ),
    ]
