# Generated by Django 3.0.2 on 2020-02-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number',
        ),
    ]
