# Generated by Django 3.0.2 on 2020-02-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='modify',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
