# Generated by Django 3.0.2 on 2020-03-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200229_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='reason',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.CharField(default='2020.01.01', max_length=200),
        ),
    ]
